version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: forum/app
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_PORT}:80"
    networks:
      - fnet
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: forum/node
    volumes:
      - .:/var/www/html
    networks:
      - fnet
  mysql:
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - fnet
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    networks:
      - fnet
networks:
  fnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"